### ISSUE TITLE
Update - outdated PG Wire Python example in  develop > insert data

### ISSUE THREAD

**Issue by amyshwang** [questdb/questdb.io#999]
**Location:**
In [Insert data](https://questdb.io/docs/develop/insert-data/#postgresql-wire-protocol), the Python code block mentions:

```
This example uses the [psycopg2](https://github.com/psycopg/psycopg2) database adapter, which does not support prepared statements (bind variables). This functionality is on the roadmap for the antecedent [psychopg3](https://github.com/psycopg/psycopg3/projects/1) adapter.
```

The information is outdated and example needs to be updated

**Screenshots:**
![image](https://user-images.githubusercontent.com/107401731/184915733-f5c7826e-2119-4aac-891d-6f58d8625535.png)

**Comment by amyshwang** [comment]
Using [psycopg documentation](https://www.psycopg.org/psycopg3/docs/basic/usage.html) I have this:


```
import psycopg as pg
import datetime as dt

# Connect to an existing QuestDB instance

with pg.connect("user=admin password=quest host=127.0.0.1 port=8812 dbname=qdb") as connection:
    # Open a cursor to perform database operations
    with connection.cursor() as cur:
        # Execute a command: this creates a new table
        cur.execute('''CREATE TABLE IF NOT EXISTS test_pg (
        ts TIMESTAMP, date DATE, name STRING, value INT)
        timestamp(ts);''')
        # Insert data into the table.

        # for x in range(10):
        #     now = dt.datetime.utcnow()
        #     date = dt.datetime.now().date()
        #     cur.execute("""
        #         INSERT INTO test_pg
        #             VALUES (%s, %s, %s, %s);
        #         """,
        #         (now, date, 'python example', x))
        cur.execute("INSERT INTO test_pg VALUES (2022, 2022, 'test test', 0);")
        # Query the database and obtain data as Python objects.
        cur.execute("SELECT * FROM test_pg")
        cur.fetchall()

        for record in cur:
            print(record)
        
    connection.commit()
```

Problems:
- I cannot get `for x in range` works
- My alternative `cur.execute("INSERT INTO test_pg VALUES (2022, 2022, 'test test', 0);")` works
- I cannot get python to print the result, so something here is not working:

```
        cur.execute("SELECT * FROM test_pg")
        cur.fetchall()

        for record in cur:
            print(record)
```
However the row can be found in the table when I access it from web console.

**Comment by amyshwang** [comment]
I got this inserted:
```cur.execute("INSERT INTO test_pg VALUES (2022, 2022, 'test test', 0);")```

Moving on to use [parameters](https://www.psycopg.org/psycopg3/docs/basic/params.html#query-parameters):

```
        for x in range(10):
            now = dt.datetime.utcnow()
            date = dt.datetime.now().date()
            cur.execute('''
                INSERT INTO test_pg
                    VALUES (%s, %s, %s, %s);
                ''',
                (2022, 2022, 'python example', x))
```
The above works, although the date and time output is problematic: 
```(datetime.datetime(1970, 1, 1, 0, 0, 0, 2022), datetime.datetime(1970, 1, 1, 0, 0, 2, 22000), 'python example', 8)```

The original code uses `date` and `now` creates this error:

```
Table created.
2022-11-14 14:54:34.869758
2022-11-14
Traceback (most recent call last):
  File "/Users/work/Repos/python_amy/pg.py", line 25, in <module>
    cur.execute('''
  File "/opt/homebrew/lib/python3.10/site-packages/psycopg/cursor.py", line 725, in execute
    raise ex.with_traceback(None)
psycopg.DatabaseError: `
message contents do not agree with length in message type "E"
```
The code is:

```
        for x in range(10):
            now = dt.datetime.utcnow()
            date = dt.datetime.now().date()
            cur.execute('''
                INSERT INTO test_pg
                    VALUES (%s, %s, %s, %s);
                ''',
                (now, date, 'python example', x))

```

The whole script:

```
import psycopg as pg
import datetime as dt

# Connect to an existing QuestDB instance

with pg.connect("user=admin password=quest host=127.0.0.1 port=8812 dbname=qdb", autocommit=True) as connection:
    # Open a cursor to perform database operations
    with connection.cursor() as cur:
        # Execute a command: this creates a new table
        cur.execute('''CREATE TABLE IF NOT EXISTS test_pg (
        ts TIMESTAMP, date DATE, name STRING, value INT)
        timestamp(ts);''')
        print ('Table created.')

        now = dt.datetime.utcnow()
        date = dt.datetime.now().date()
        print(now)
        print(date)

        # Insert data into the table.

        for x in range(10):
            now = dt.datetime.utcnow()
            date = dt.datetime.now().date()
            cur.execute('''
                INSERT INTO test_pg
                    VALUES (%s, %s, %s, %s);
                ''',
                (2022, 2022, 'python example', x))

        #Query the database and obtain data as Python objects.

        print ('Rows inserted.')
        cur.execute("SELECT * FROM test_pg")
        for record in cur:
            print(record)
```
